name: medical_corner
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  adaptive_dialog: ^2.1.0
  animated_splash_screen: ^1.2.0
  bloc: ^8.0.3
  cloud_firestore: ^4.17.2
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_ml_model_downloader: ^0.2.5+3
  firebase_storage: ^11.7.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.10+1
  google_sign_in: ^6.2.1
  hexcolor: ^3.0.1
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.0
  intl: ^0.19.0
  lottie: ^3.1.0
  page_transition: ^2.1.0
  permission_handler: ^11.3.1
  provider: ^6.0.2
  screenshot: ^2.3.0
  shared_preferences: ^2.0.13
  tflite: ^1.1.2

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/icon.png
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_launcher.png"

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie_animations/
    - assets/tflite_models/
  fonts:
    - family: seguisb
      fonts:
        - asset: assets/seguisb.ttf
